let all_product = [
  {
    id: 1,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866691/product_1_elvv4s.png",
    new_price: 50.0,
    old_price: 80.5,
  },
  {
    id: 2,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_2_vgn2hf.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 3,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_3_smpmpk.png",
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    id: 4,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_4_cgi8uv.png",
    new_price: 100.0,
    old_price: 150.0,
  },
  {
    id: 5,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_5_glhtlj.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_6_ky0lns.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 7,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866693/product_7_akxjd3.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 8,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866693/product_8_pmmyda.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 9,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866693/product_9_nj1t1j.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 10,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866694/product_10_dhbshw.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_11_dxlluz.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 12,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866694/product_12_pku4mh.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 13,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_13_j4yv5u.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 14,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866697/product_14_scedtd.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 15,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_15_rhpz6l.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 16,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866696/product_16_y6jl7m.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 17,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_17_umm7l1.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 18,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866696/product_18_skylvn.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 19,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866696/product_19_ofsdtc.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 20,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_20_n8tane.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 21,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_21_xanuw3.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 22,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866692/product_22_d5otf0.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 23,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866693/product_23_ijwfbj.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 24,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866693/product_24_vxzwlh.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 25,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866694/product_25_ifpdia.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 26,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866694/product_26_jnssnd.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 27,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866694/product_27_iqdhqk.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 28,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_28_vzqoyc.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 29,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_29_l0ej32.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 30,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_30_fypckj.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 31,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866695/product_31_zgethi.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 32,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866697/product_32_aulobx.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 33,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866696/product_33_vjgohj.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 34,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866696/product_34_u6fy0s.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 35,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866697/product_35_ivbz2m.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 36,
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: "https://res.cloudinary.com/dgjqzpzoe/image/upload/v1762866698/product_36_lgoemz.png",
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
